import { v4 as uuid } from "uuid";

export const shipments = [
  {
    id: uuid(),
    shipFromAddress: {
      country: "USA",
      state: "West Virginia",
      city: "Parkersburg",
      street: "2849 Fulton Street",
    },
    shipToAddress: {
      country: "USA",
      state: "West Virginia",
      city: "Parkersburg",
      street: "2849 Fulton Street",
    },
    itemQuantity: 36,
    trackingNumber: "278899124033",
    shipmentCost: 3590,
    carrier: "fedex",
    status: "UNKOWN",
    createdAt: 1555016400000,
    userEmail: "ekaterina.tankova@devias.io",
    packageDimensions: {
      length: 10,
      width: 20,
      height: 15,
    },
  },
  {
    id: uuid(),
    shipFromAddress: {
      country: "USA",
      state: "West Virginia",
      city: "Parkersburg",
      street: "2849 Fulton Street",
    },
    shipToAddress: {
      country: "USA",
      state: "West Virginia",
      city: "Parkersburg",
      street: "2849 Fulton Street",
    },
    itemQuantity: 36,
    trackingNumber: "1Z4732A70331073109",
    shipmentCost: 3590,
    carrier: "ups",
    status: "PRE_TRANSIT",
    createdAt: 1555016400000,
    userEmail: "ekaterina.tankova@devias.io",
    packageDimensions: {
      length: 10,
      width: 20,
      height: 15,
    },
  },
  {
    id: uuid(),
    shipFromAddress: {
      country: "USA",
      state: "West Virginia",
      city: "Parkersburg",
      street: "2849 Fulton Street",
    },
    shipToAddress: {
      country: "USA",
      state: "West Virginia",
      city: "Parkersburg",
      street: "2849 Fulton Street",
    },
    itemQuantity: 36,
    trackingNumber: "92055901755477300040390825",
    shipmentCost: 3590,
    carrier: "usps",
    status: "TRANSIT",
    createdAt: 1555016400000,
    userEmail: "ekaterina.tankova@devias.io",
    packageDimensions: {
      length: 10,
      width: 20,
      height: 15,
    },
  },
  {
    id: uuid(),
    shipFromAddress: {
      country: "USA",
      state: "West Virginia",
      city: "Parkersburg",
      street: "2849 Fulton Street",
    },
    shipToAddress: {
      country: "USA",
      state: "West Virginia",
      city: "Parkersburg",
      street: "2849 Fulton Street",
    },
    itemQuantity: 36,
    trackingNumber: "278899124033",
    shipmentCost: 3590,
    carrier: "fedex",
    status: "DELIVERED",
    createdAt: 1555016400000,
    userEmail: "ekaterina.tankova@devias.io",
    packageDimensions: {
      length: 10,
      width: 20,
      height: 15,
    },
  },
  {
    id: uuid(),
    shipFromAddress: {
      country: "USA",
      state: "West Virginia",
      city: "Parkersburg",
      street: "2849 Fulton Street",
    },
    shipToAddress: {
      country: "USA",
      state: "West Virginia",
      city: "Parkersburg",
      street: "2849 Fulton Street",
    },
    itemQuantity: 36,
    trackingNumber: "1Z4732A70331073109",
    shipmentCost: 3590,
    carrier: "ups",
    status: "RETURNED",
    createdAt: 1555016400000,
    userEmail: "ekaterina.tankova@devias.io",
    packageDimensions: {
      length: 10,
      width: 20,
      height: 15,
    },
  },
  {
    id: uuid(),
    shipFromAddress: {
      country: "USA",
      state: "West Virginia",
      city: "Parkersburg",
      street: "2849 Fulton Street",
    },
    shipToAddress: {
      country: "USA",
      state: "West Virginia",
      city: "Parkersburg",
      street: "2849 Fulton Street",
    },
    itemQuantity: 36,
    trackingNumber: "92055901755477300040390825",
    shipmentCost: 3590,
    carrier: "usps",
    status: "FAILURE",
    createdAt: 1555016400000,
    userEmail: "ekaterina.tankova@devias.io",
    packageDimensions: {
      length: 10,
      width: 20,
      height: 15,
    },
  },
];
